default_platform(:ios)

platform :ios do
  # Match
  desc "Setup development certificates"
  lane :setup_development_certificates do
    keychain
    match(
      type: "development",
    )
  end

  # Utility
  desc "Update MARKETING_VERSION & CURRENT_PROJECT_VERSION"
  lane :update_app_version do
    ["App/AdHoc/AdHoc.xcodeproj", "App/Production/Production.xcodeproj", "App/Develop/Develop.xcodeproj"].each do |xcodeproj|
      version = get_build_number(
        xcodeproj: xcodeproj,
      )
      update_xcodeproj(
        xcodeproj: xcodeproj,
        options: {
          "CURRENT_PROJECT_VERSION": version.to_i + 1,
          "MARKETING_VERSION": "1.3.1",
        }
      )
    end
  end
end
