name: AdHoc

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  adhoc:
    runs-on: xcode-27

    env:
      DEVELOPER_DIR: /Applications/Xcode_27.1_beta.app/Contents/Developer
      APP_NAME: WebSocketClient
      SCHEME: AdHoc

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        submodules: "recursive"

    - name: Get SwiftPM originHash
      id: get-swiftpm-origin-hash
      run: |
        ORIGIN_HASH="$(jq -c -r '.originHash' WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved)"
        echo "ORIGIN_HASH=${ORIGIN_HASH}" >> "${GITHUB_OUTPUT}"

    - name: Cache Swift Packages
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: cache-swiftpm
      timeout-minutes: 20
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ steps.get-swiftpm-origin-hash.outputs.ORIGIN_HASH }}

    - name: Write IDESkipPackagePluginFingerprintValidatation
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

    - name: Write IDESkipMacroFingerprintValidation
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

    - name: Setup AuthKey
      env:
        APP_STORE_CONNECT_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_P8_BASE64 }}
        KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      run: |
        mkdir -p ~/.appstoreconnect/private_keys
        echo "${APP_STORE_CONNECT_API_KEY_P8_BASE64}" | base64 -d > ~/.appstoreconnect/private_keys/AuthKey_"${KEY_ID}".p8
        chmod 600 ~/.appstoreconnect/private_keys/AuthKey_"${KEY_ID}".p8

    - name: Xcodebuild showBuildSettings
      id: show-build-settings
      run: |
        ./ci_scripts/get_marketing_version.sh \
          "${APP_NAME}" \
          "${SCHEME}"

    - name: Build AdHoc.ipa
      env:
        VERSION: ${{ steps.show-build-settings.outputs.marketing_version }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        GIT_PRIVATE_KEY_BASE64: ${{ secrets.GIT_PRIVATE_KEY_BASE64 }}
        KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        FASTLANE_SKIP_UPDATE_CHECK: 1
        MATCH_KEYCHAIN_NAME: "fastlane_keychain"
        MATCH_KEYCHAIN_PASSWORD: ""
      run: |
        MATCH_GIT_PRIVATE_KEY=$(echo -n "${GIT_PRIVATE_KEY_BASE64}" | base64 -d)
        export MATCH_GIT_PRIVATE_KEY
        fastlane ios setup_development_certificates
        ./ci_scripts/archive_export.sh \
          "${APP_NAME}" \
          "${SCHEME}" \
          "${VERSION}" \
          "${KEY_ID}" \
          "${ISSUER_ID}" \
          "./App/${SCHEME}/${SCHEME}/Resources/GoogleService-Info.plist"

    - name: Upload ipa to Firebase AppDistribution
      env:
        APP_ID: 1:89035443908:ios:2b6115971af3118435c391
        APP_DISTRIBUTION_KEY_BASE64: ${{ secrets.APP_DISTRIBUTION_KEY_BASE64 }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/app-distribution-key.json
      run: |
        echo "${APP_DISTRIBUTION_KEY_BASE64}" | base64 -d > /tmp/app-distribution-key.json
        ./ci_scripts/firebase_distribution.sh \
          "${SCHEME}" \
          "${APP_ID}"

    - name: Upload Products
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: websocket-client-adhoc
        path: Products
