name: AppStore

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  appstore:
    runs-on: macos-13

    env:
      FASTLANE_SKIP_UPDATE_CHECK: 1

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        xcodebuild -version

    - name: Cache Swift Packages
      uses: actions/cache@v3
      id: cache-swiftpm
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

    - name: Write IDESkipPackagePluginFingerprintValidatation
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

    - name: Setup app-store-connect-api-key.json
      env:
        APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
      run: echo "${APP_STORE_CONNECT_API_KEY_BASE64}" | base64 -d > /tmp/app-store-connect-api-key.json

    - name: Fastlane release
      env:
        FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 20
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_KEYCHAIN_NAME: "fastlane_keychain"
        MATCH_KEYCHAIN_PASSWORD: ""
        APP_STORE_CONNECT_API_KEY_PATH: /tmp/app-store-connect-api-key.json
        GIT_PRIVATE_KEY_BASE64: ${{ secrets.GIT_PRIVATE_KEY_BASE64 }}
      run: |
        MATCH_GIT_PRIVATE_KEY=$(echo -n "${GIT_PRIVATE_KEY_BASE64}" | base64 -d)
        export MATCH_GIT_PRIVATE_KEY
        bundle exec fastlane release

    - name: Upload Products
      uses: actions/upload-artifact@v3
      with:
        name: websocket-client-appstore
        path: Products

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Products/WebSocketClient.ipa
          Products/WebSocketClient.app.dSYM.zip
        generate_release_notes: true
