name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: macos-14

    permissions:
      pull-requests: write
      issues: write
      statuses: write
      checks: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache SwiftLint
      uses: actions/cache@v4
      id: cache-swiftlint
      with:
        path: swiftlint
        key: ${{ runner.os }}-swiftlint-${{ hashFiles('swiftlint/swiftlint') }}

    - name: Download SwiftLint
      if: steps.cache-swiftlint.outputs.cache-hit != 'true'
      run: |
        version=$(jq -r '.pins[] | select( .identity == "swiftlint" ) | .state.version' < WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved)
        mkdir swiftlint
        cd swiftlint
        wget "https://github.com/realm/SwiftLint/releases/download/${version}/portable_swiftlint.zip"
        unzip portable_swiftlint.zip
        cd -

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        # ruby-version: "3.2"
        bundler-cache: true

    - name: Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
