name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: macos-15

    permissions:
      pull-requests: write
      issues: write
      statuses: write
      checks: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Cache SwiftLint
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      id: cache-swiftlint
      with:
        path: swiftlint
        key: ${{ runner.os }}-swiftlint-${{ hashFiles('swiftlint/swiftlint') }}

    - name: Download SwiftLint
      if: steps.cache-swiftlint.outputs.cache-hit != 'true'
      run: |
        version=$(jq -r '.pins[] | select( .identity == "swiftlintplugins" ) | .state.version' < WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved)
        mkdir swiftlint
        cd swiftlint
        wget "https://github.com/realm/SwiftLint/releases/download/${version}/portable_swiftlint.zip"
        unzip portable_swiftlint.zip
        cd -

    - name: Setup Ruby
      uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
      with:
        ruby-version: "4.0.1"
        bundler-cache: true

    - name: Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger
