name: Renovate

on:
  pull_request:
    paths:
      - WebSocketClientPackage/Package.swift

jobs:
  precheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      files_changes: ${{ steps.files_changes.outputs.files }}
    steps:
    - uses: actions/checkout@v3

    - uses: trilom/file-changes-action@v1
      id: files_changes

  resolve-swift-packages:
    runs-on: macos-13
    needs: precheck
    if: contains(fromJson(needs.precheck.outputs.files_changes), 'Package.resolved') == false

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        xcodebuild -version

    - name: Cache Swift Packages
      uses: actions/cache@v3
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -scheme WebSocketClient -workspace WebSocketClient.xcworkspace -clonedSourcePackagesDirPath .swiftpm

    - name: Git Config
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Commit & Push
      env:
        HEAD_REF: ${{ github.head_ref }}
      run: |
        git add WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved
        if git commit -m "Resolve Swift Package"; then
          git push origin "HEAD:${HEAD_REF}"
        fi
