name: Renovate

on:
  pull_request:
    paths:
      - WebSocketClientPackage/Package.swift

jobs:
  precheck:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    outputs:
      files_changes: ${{ steps.files_changes.outputs.files }}

    steps:
    - uses: actions/checkout@v3

    - uses: trilom/file-changes-action@v1.2.4
      id: files_changes

  resolve-swift-packages:
    runs-on: macos-13
    needs: precheck
    if: contains(fromJson(needs.precheck.outputs.files_changes), 'WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') == false

    steps:
    - uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/nnsnodnb/github-apps-token-swift
        version: '*'

    - name: Configure Access Token for GitHub Apps
      env:
        APP_ID: ${{ secrets.APP_ID }}
        PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      run: |
        cat << "EOF" > /tmp/github-apps-private-key.pem
        ${PRIVATE_KEY}
        EOF
        token=$(github-apps-token create \
                  -a "${APP_ID}" \
                  -p /tmp/github-apps-private-key.pem \
                  --owner nnsnodnb \
                  -r websocket-client-ios \
                  --contents write)
        echo "GITHUB_APPS_TOKEN=${token}" >> "${GITHUB_ENV}"
        rm /tmp/github-apps-private-key.pem

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${GITHUB_APPS_TOKEN}

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        xcodebuild -version

    - name: Cache Swift Packages
      uses: actions/cache@v3
      timeout-minutes: 20
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

    - name: Resolve Swift Packages
      run: xcodebuild -resolvePackageDependencies -scheme WebSocketClient -workspace WebSocketClient.xcworkspace -clonedSourcePackagesDirPath .swiftpm

    - name: Git Config
      run: |
        git config --global user.email "aoi-chan-bot[bot]@users.noreply.github.com"
        git config --global user.name "aoi-chan-bot[bot]"

    - name: Commit & Push
      env:
        HEAD_REF: ${{ github.head_ref }}
        GITHUB_TOKEN: ${GITHUB_APPS_TOKEN}
      run: |
        git add WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved
        if git commit -m "Resolve Swift Package"; then
          git push origin "HEAD:${HEAD_REF}"
        fi

    - name: Revoke Access Token for GitHub Apps
      if: success() || failure()
      run: github-apps-token revoke --token "${GITHUB_APPS_TOKEN}"
