name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-15

    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Cache Swift Packages
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache-swiftpm
        with:
          path: .swiftpm
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

      - name: Write IDESkipPackagePluginFingerprintValidatation
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Write IDESkipMacroFingerprintValidation
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: Make test-result folder
        run: mkdir -p test-results

      - name: Xcode test
        run: |
          set -o pipefail && \
            xcodebuild test \
              -scheme WebSocketClientPackageTests \
              -workspace WebSocketClient.xcworkspace \
              -parallel-testing-enabled=YES \
              -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
              -resultBundlePath "Test-WebSocketClientPackageTests.xcresult" \
              -clonedSourcePackagesDirPath .swiftpm \
              -disableAutomaticPackageResolution | xcpretty
