name: Test

on:
  pull_request:
    paths-ignore:
      - .github/workflows/adhoc.yml
      - .github/workflows/appstore.yml
      - .github/workflows/lint.yml
      - .github/workflows/renovate.yml
      - LICENSE
      - README.md
      - renovate.json

jobs:
  test:
    runs-on: macos-13

    env:
      FASTLANE_SKIP_UPDATE_CHECK: 1

    permissions:
      checks: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true

    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_14.3.1.app/Contents/Developer
        xcodebuild -version

    - name: Cache Swift Packages
      uses: actions/cache@v3
      id: cache-swiftpm
      timeout-minutes: 20
      with:
        path: .swiftpm
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}

    - name: Write IDESkipPackagePluginFingerprintValidatation
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

    - name: Copy Package.resolve from workspace
      run: cp WebSocketClient.xcworkspace/xcshareddata/swiftpm/Package.resolved WebSocketClientPackage

    - name: xcodebuild test
      working-directory: WebSocketClientPackage
      env:
        DEVICE_NAME: iPhone 14 Pro Max
        OS: 16.4
      run: |
        rm -rf TestResults.xctest
        set -o pipefail && env NSUnbufferedIO=YES xcodebuild test clean \
          -scheme WebSocketClientPackage \
          -clonedSourcePackagesDirPath ../.swiftpm \
          -disableAutomaticPackageResolution \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,OS=${OS},name=${DEVICE_NAME}" \
          -resultBundlePath TestResults.xcresult | bundle exec xcpretty

    - name: Publish unit test results
      uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: WebSocketClientPackage/TestResults.xcresult
        show-passed-tests: false
        show-code-coverage: false
